//Generated By: OpenCube - Visual DHTML, Copyright (c) 2001, OpenCube Inc. All Rights Reserved.
//
//-----OpenCube Copyright Notice Parameter----
//Notice = "DHTML Navigation Menu, Copyright (c) - 2001, OpenCube Inc. - www.opencube.com"

//-----NOTE: We are only using this configuration file for our navigational path// menu.  This menu was not developed by OpenCube.

//----- LBA-ECO Configurable Variables -------
baseURL = "/lbaeco/";
cgiURL = "/cgi-bin/";

//-------Specific Settings--------------------
// Main Menu:
url0 = baseURL+"invest.htm";
url1 = baseURL+"data.htm";
url2 = baseURL+"logist.htm";
url3 = baseURL+"sites.htm";
url4 = baseURL+"out.htm";
url5 = baseURL+"comm.htm";
url6 = cgiURL+'web/admin/admin.pl';

//INVESTIGATOR

subdesc0_0 = "Sign In or Create Account"
url0_0 = cgiURL+"sign_in/sign_in.pl?igi=1"
subdesc0_0_0 = "View Account Menu"
url0_0_0 = cgiURL+"sign_in/sign_in.pl?show_menu=1"
subdesc0_0_1 = "Update Your Personnel Information"
url0_0_1 = cgiURL+"pdb/update_person.pl"
subdesc0_0_2 = "Request to join Project Groups"
url0_0_2 = cgiURL+"pdb/add_group.pl"
subdesc0_0_3 = "Change Your Password"
url0_0_3 = cgiURL+"sign_in/change_pw.pl"
subdesc0_0_4 = "Sign In Tips"
url0_0_4 = baseURL+"invest/signin/sign_tips.htm"


subdesc0_1 = "Agreements and Responsibilities"
url0_1 = baseURL+"invest/invest_resp.htm"
subdesc0_2 = "The Investigator's Checklist"
url0_2 = baseURL+"invest/invest_check.htm"
subdesc0_3 = "Investigations"
url0_3 = baseURL+"invest/invest_res.htm"
subdesc0_3_0 = "Abstracts and Profiles"
url0_3_0 = cgiURL+"web/investigations/inv_abstracts.pl"
subdesc0_3_1 = "Student Participation"
url0_3_1 = baseURL+"out/train/out_train_stu.htm"
subdesc0_3_2 = "LBA-Air-ECO"
url0_3_2 = baseURL+"invest/invest_air.htm"
subdesc0_3_3 = "LBA-HYDROMET"
url0_3_3 = baseURL+"invest/invest_hydro.htm"
subdesc0_3_4 = "Science Themes"
url0_3_4 = baseURL+"invest/invest_theme.htm"
subdesc0_3_5 = "Science Questions"
url0_3_5 = cgiURL+"web/explan/science_questions.pl"
subdesc0_3_6 = "What are Investigation Codes?"
url0_3_6 = baseURL+"invest/invest_code.htm"
subdesc0_4 = "Documents and Reports"
url0_4 = baseURL+"invest/invest_docs.htm"
subdesc0_5 = "Publications"
url0_5 = baseURL+"invest/invest_pubs.htm"
subdesc0_6 = "CNPq Licence"
url0_6 = baseURL+"invest/invest_cnpq.htm"
        

//DATA

subdesc1_0 ="About LBA-DIS"
url1_0 = baseURL+"data/data_dis.htm"
subdesc1_1 = "Data Process Overview"
url1_1 = baseURL+"data/data_proc.htm"
subdesc1_2 = "Transfer Data to CPTEC"
url1_2 = baseURL+"data/data_sub.htm"
subdesc1_3 = "Register Your Metadata"
url1_3 = baseURL+"data/data_reg.htm"
subdesc1_4 = "Find LBA Data"
url1_4 = baseURL+"data/data_lba.htm"
subdesc1_5 = "Investigator Obligations"
url1_5 = baseURL+"data/data_pol.htm"
subdesc1_6 = "Contact for Data Questions"
url1_6 = baseURL+"data/data_con.htm"

//LOGISTICS

//Schedule Site Visit

subdesc2_0 = "Schedule STI Site Visit"
url2_0 = cgiURL+"stdb/scheduler/scheduler_signin.pl"
subdesc2_0_0 = "Help, example"
url2_0_0 = baseURL+"/invest/signin/sti_help.htm"

//FIELD SUPPORT

subdesc2_1 = "Field Support"
url2_1 = baseURL+"logist/field.htm"
subdesc2_1_0 = "Support at the Sites"
url2_1_0 = baseURL+"sites.htm"
subdesc2_1_1 = "General Orientation Manuals"
url2_1_1 = baseURL+"logist/field/field_orient.htm"
subdesc2_1_2 = "Vehicles"
url2_1_2 = cgiURL+"web/sites/vehicles.pl"
subdesc2_1_3 = "Accompaniment"
url2_1_3 = baseURL+"logist/field/field_accom.htm"
subdesc2_1_4 = "Permits"
url2_1_4 = baseURL+"logist/field/field_permit.htm"
subdesc2_1_5 = "Emergency and First Aid"
url2_1_5 = baseURL+"logist/field/field_safe.htm"
subdesc2_1_6 = "Tower Training"
url2_1_6 = baseURL+"logist/field/field_tower.htm"
subdesc2_1_7 = "Site Resources Coordination"
url2_1_7 = cgiURL+"web/sites/site_coord_report.pl"
subdesc2_1_8 = "Gas Tracking"
url2_1_8 = cgiURL+"calgas/calib_main.pl"
subdesc2_1_9 = "Satellite Phone Use"
url2_1_9 = baseURL+"logist/field/sat_com.htm"

//VISA

subdesc2_2 = "The Visa Process"
url2_2 = baseURL+"logist/visa.htm"


//TRAVEL

subdesc2_3 = "Critical Travel Info "
url2_3 = baseURL+"logist/travel.htm"
subdesc2_3_0 = "LBA-ECO Travel Checklist"
url2_3_0 = baseURL+"logist/travel/trav_check.htm"
subdesc2_3_0_0 = "Passport"
url2_3_0_0 = baseURL+"logist/travel/trav_pass.htm"
subdesc2_3_0_1 = "Curriculum Vitae"
url2_3_0_1 = baseURL+"logist/travel/trav_cv.htm"
subdesc2_3_0_2 = "Good Conduct Certification"
url2_3_0_2 = baseURL+"logist/visa/visa_con.htm"
subdesc2_3_0_3 = "LBA Vitem-I Visa"
url2_3_0_3 = baseURL+"logist/visa/visa_check.htm"
subdesc2_3_0_4 = "Immunization"
url2_3_0_4 = baseURL+"logist/travel/trav_immun.htm"
subdesc2_3_0_5 = "Entry/Departure Card"
url2_3_0_5 = baseURL+"logist/travel/trav_entry.htm"
subdesc2_3_0_6 = "Federal Police Registration"
url2_3_0_6 = baseURL+"logist/visa/visa_fed_pol.htm"
subdesc2_3_0_7 = "US Consulate Registration"
url2_3_0_7 = baseURL+"logist/travel/trav_consul.htm"
subdesc2_3_1 = "Driving"
url2_3_1 = baseURL+"logist/travel/trav_driv.htm"
subdesc2_3_1_0 = "How to Change a Tire"
url2_3_1_0 = baseURL+"logist/travel/como_trocar.pdf"
subdesc2_3_1_1 = "Obtain a Valid Temp Brazilian License"
url2_3_1_1 = baseURL+"logist/travel/trav_driv_lic.htm"
subdesc2_3_1_2 = "Driving Customs"
url2_3_1_2 = baseURL+"logist/travel/trav_driv_cust.htm"
subdesc2_3_1_3 = "New Traffic Laws"
url2_3_1_3 = baseURL+"logist/travel/trav_driv_law.htm"
subdesc2_3_1_4 = "Auto Accidents"
url2_3_1_4 = baseURL+"logist/travel/trav_driv_acc.htm"
subdesc2_3_2 = "In-Country Living"
url2_3_2 = baseURL+"logist/travel/trav_liv.htm"
subdesc2_3_2_0 = "Mail"
url2_3_2_0 = baseURL+"logist/travel/trav_liv_mail.htm"
subdesc2_3_2_1 = "Phones"
url2_3_2_1 = baseURL+"logist/travel/trav_liv_tele.htm"
subdesc2_3_2_2 = "Electric"
url2_3_2_2 = baseURL+"logist/travel/trav_liv_elec.htm"
subdesc2_3_2_3 = "Tipping"
url2_3_2_3 = baseURL+"logist/travel/trav_liv_tip.htm"
subdesc2_3_2_4 = "Holidays"
url2_3_2_4 = baseURL+"logist/travel/trav_liv_holid.htm"
subdesc2_3_3 = "Legal Considerations"
url2_3_3 = baseURL+"logist/travel/trav_legal.htm"
subdesc2_3_4 = "Travel Warnings"
url2_3_4 = baseURL+"logist/travel/trav_warn.htm"

//SHIPPING

subdesc2_4 = "Shipping Procedures"
url2_4 = baseURL+"logist/ship.htm"

//SITES

subdesc3_0 = "Site Specific Information"
url3_0 = baseURL+"sites.htm"

subdesc3_1 = "Schedule STI Site Visit"
url3_1 = cgiURL+"stdb/scheduler/scheduler_signin.pl"

subdesc3_1_0 = "Help, example"
url3_1_0 = baseURL+"/invest/signin/sti_help.htm"

subdesc3_2 = "Site Visit Reports"
url3_2 = baseURL+"sites/site_reports.htm"

subdesc3_2_0 = "Who's Doing What, Where and When?"
url3_2_0 = cgiURL+"stdb/scheduler_report.pl"

subdesc3_2_1 = "Logistics Request Reports"
url3_2_1 = cgiURL+"stdb/scheduler_logist_report.pl"

subdesc3_3 = "Tower Statistics"
url3_3 = cgiURL+"web/sites/towers.pl"



//OUTREACH

subdesc4_0 = "News and Events"
url4_0 = baseURL+"out/out_news.htm"
//subdesc4_0_0 = "Fortaleza Conference"
//url4_0_0 = baseURL+"out/out_news/conf110503/conf_welc.htm"

subdesc4_1 = "About LBA"
url4_1 = baseURL+"out/out_lba.htm"
subdesc4_2 = "Training and Education"
url4_2 = baseURL+"out/out_train.htm" 
subdesc4_2_0 = "Goals"
url4_2_0 = baseURL+"out/train/out_train_goals.htm" 
subdesc4_2_1 = "Opportunities"
url4_2_1 = baseURL+"out/train/out_train_opp.htm"   
subdesc4_2_2 = "Activities by LBA-ECO Research Teams"
url4_2_2 = baseURL+"out/out_train.htm"
subdesc4_3 = "Resources"
url4_3 = baseURL+"out/out_res.htm"
subdesc4_3_0 = "Photos"
url4_3_0 = cgiURL+"photo_archive/photo_arch_main.pl?smart_search_photo=1"
subdesc4_3_1 = "Presentations"
url4_3_1 = baseURL+"out/out_res.htm"
subdesc4_3_2 = "Newsletters, Pamphlets"
url4_3_2 = baseURL+"out/out_res.htm"
subdesc4_3_3 = "Posters"
url4_3_3 = baseURL+"out/out_res.htm"
subdesc4_3_4 = "Movies"
url4_3_4 = baseURL+"out/out_res.htm"
subdesc4_3_5 = "Articles"
url4_3_5 = baseURL+"out/out_res.htm"


//Contact


subdesc5_0 = "Project Office"
url5_0 = baseURL+"comm/comm_po"
subdesc5_1 = "Find People"
url5_1 = cgiURL+"pdb/find_set.pl"
subdesc5_2 = "Email Lists"
url5_2 = cgiURL+"web/email_lists/web_email_lists.pl"

//ADMIN

subdesc6_0 = "Admin"
url6_0 = cgiURL+"pdb/admin/admin_options.pl"

//----------------------------------------
//----- LBA-ECO Customization ------------
//----------------------------------------


//----- Top Level Menu Array -------------
// For each image at the top level of the menu,
// add an element (in order) to the array, 
// containing the following unique values:
// the header and the URL to the page.  

topLevel = new Array();
	topLevel[0] = new Array ("Investigator", window.baseURL+"invest.htm");
	topLevel[1] = new Array ("Data", window.baseURL+"data.htm");
	topLevel[2] = new Array ("Logistics", window.baseURL+"logist.htm");
	topLevel[3] = new Array ("Sites", window.baseURL+"sites.htm");
	topLevel[4] = new Array ("Outreach", window.baseURL+"out.htm");
	topLevel[5] = new Array ("Contact", window.baseURL+"comm.htm");
	topLevel[6] = new Array ("Administrative Tools", window.cgiURL+"web/admin/admin.pl");

//----- Page Nickname Array -------------
// For every new virtual hierarchical path
// (path traveled by the user to the page)
// add a new element to the array, containing 
// the following unique values: array number
// (in the square [] brackets), page nickname 
// and the number following the associated subdesc.
// For the number in the square brackets, add 1 to
// the highest number used. VERY IMPORTANT: All the
// numbers in a squence (from 1 to n) must be used.
// Numbers cannot be skipped, or the path menu 
// will not work.  Also, do not forget to add the
// semi colon after the statement.

assoc_page = new Array();

        assoc_page[0] = new Array ("invest", "0");
 	assoc_page[1] = new Array ("investsign", "0_0");
	assoc_page[2] = new Array ("investresp", "0_1");
	assoc_page[3] = new Array ("investchk", "0_2");
        assoc_page[4] = new Array ("investres", "0_3");
        assoc_page[5] = new Array ("investcode", "0_3_0"); 
	assoc_page[6] = new Array ("investabs", "0_3_1");

        assoc_page[7] = new Array ("investdocs", "0_4");
        assoc_page[8] = new Array ("investnews", "0_5");
        assoc_page[9] = new Array ("commfp", "5_1");
        assoc_page[10] = new Array ("investpub", "0_7"); 
//data
        assoc_page[11] = new Array ("data", "1");
        assoc_page[12] = new Array ("datadis", "1_0");
        assoc_page[13] = new Array ("dataproc", "1_1");
        assoc_page[14] = new Array ("datasub", "1_2"); 
        assoc_page[15] = new Array ("datareg", "1_3"); 
        assoc_page[16] = new Array ("datalba", "1_4");
        assoc_page[17] = new Array ("dataob", "1_5");



//Logistics
        assoc_page[18] = new Array ("logist", "2");
//sitevisit        
        assoc_page[19] = new Array ("sign", "0_0");
//field support
        assoc_page[20] = new Array ("field", "2_1");
        assoc_page[21] = new Array ("sites", "3");
        assoc_page[22] = new Array ("travdriv", "2_3_1");
        assoc_page[23] = new Array ("visa", "2_2");
        assoc_page[24] = new Array ("visacheck", "2_2_1");
//travel
        assoc_page[25] = new Array ("trav", "2_3");
        assoc_page[26] = new Array ("travcheck", "2_3_0");

        assoc_page[27] = new Array ("travliv", "2_3_2");

        assoc_page[28] = new Array ("travleg", "2_3_3");
        assoc_page[29] = new Array ("travwarn", "2_3_4");


        assoc_page[30] = new Array ("ship", "2_4");
        assoc_page[31] = new Array ("sites", "3");
        assoc_page[32] = new Array ("sign", "0_0");

        assoc_page[33] = new Array ("out", "4");       

 


        assoc_page[34] = new Array ("comm", "5");

        assoc_page[35] = new Array ("commpo", "5_0");
        assoc_page[36] = new Array ("commfp", "5_1");
        assoc_page[37] = new Array ("emaillists", "5_2");
        assoc_page[38] = new Array ("schedule", "3_1");
        assoc_page[39] = new Array ("sv_reports", "3_2");
        assoc_page[40] = new Array ("calgas", "2_1_8");
        assoc_page[41] = new Array ("resources", "4_3");
        assoc_page[42] = new Array ("admin", "6_0");
        assoc_page[43] = new Array ("train", "4_2");
        assoc_page[44] = new Array ("confwelc", "4_0_0");
        assoc_page[45] = new Array ("outnews", "4_0");

        assoc_page[46] = new Array ("admintools", "6");
		
		assoc_page[47] = new Array ("cnpq", "0_6");
		

